### ISSUE TITLE
does leveling up work? or does it also require a checksumm?

### ISSUE THREAD

**Issue by nIKsL** [raelldottin/tachikoma#58]
Hi!
does crew leveling work? or does it also require a checksumm?

**Comment by nIKsL** [comment]
And does crew training work?

**Comment by raelldottin** [comment]
@nIKsL both crew training and crew leveling works.

I plan to refactor the code to use a unique identifier and automatically move the crew to their designated rooms if their training is complete or to a training room because no checksums are required for those endpoints. I have support for all the training rooms in the manageTraining method.

Crew leveling works but my implementation is too bruteforce. It attempts to upgrade each crew that's not level 40 even if the crew doesn't have enough exp for an upgrade. I have not figured out how to determine if the crew has enough exp for an upgrade. Therefore, I didn't use that method because I didn't want to produce so much necessary next traffic. 

I run my script using a GitHub action at an hour interval.

By the year, this codebase will have significant improvements.

**Comment by nIKsL** [comment]
which class method is responsible for training?
or did you remove it from the code?

I also run the script locally via cron every hour :)
In another script I implemented auto-battles via pyautogui - I’m working with the game client.

**Comment by raelldottin** [comment]
The client.manageTraining method on line 660 is the method responsible for
crew training.

In sdk/client.py:
Line 687 - 761 has a static definition for crew training.

**Comment by nIKsL** [comment]
^ I mean class method for level up, not about training

**Comment by nIKsL** [comment]
By the way, in the laboratory there is a study of rockets, which is not shown in the game client. But it is launched via API.

Its ID is 5 or something like that (can be seen from alldesign xml request)

I advise you to add it to the exception in the study.

**Comment by raelldottin** [comment]
client.upgradeCharacter

**Comment by raelldottin** [comment]
Ok, thank you. You can always submit a PR.
